version: 0.2

env:
  secrets-manager:
    AWS_ACCOUNT_ID: "arn:aws:secretsmanager:ap-northeast-1:730335258866:secret:kakeibo/backend-5LdAEs:AWS_ACCOUNT_ID"
    IMAGE_REPO_NAME: "arn:aws:secretsmanager:ap-northeast-1:730335258866:secret:kakeibo/backend-5LdAEs:IMAGE_REPO_NAME"
    AWS_DEFAULT_REGION: "arn:aws:secretsmanager:ap-northeast-1:730335258866:secret:kakeibo/backend-5LdAEs:AWS_DEFAULT_REGION"
    DB_PORT: "arn:aws:secretsmanager:ap-northeast-1:730335258866:secret:kakeibo/backend-5LdAEs:"
    DB_HOST: "arn:aws:secretsmanager:ap-northeast-1:730335258866:secret:kakeibo/backend-5LdAEs:DB_HOST"
    DB_NAME: "arn:aws:secretsmanager:ap-northeast-1:730335258866:secret:kakeibo/backend-5LdAEs:DB_NAME"
    DB_PASSWORD: "arn:aws:secretsmanager:ap-northeast-1:730335258866:secret:kakeibo/backend-5LdAEs:DB_PASSWORD"
    DB_USER: "arn:aws:secretsmanager:ap-northeast-1:730335258866:secret:kakeibo/backend-5LdAEs:DB_USER"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Move Directory
      - cd ./backend
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build --build-arg DB_PORT=$DB_PORT --build-arg DB_HOST=$DB_HOST --build-arg DB_NAME=$DB_NAME --build-arg DB_PASSWORD=$DB_PASSWORD --build-arg DB_USER=$DB_USER -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...

artifacts:
  files: 
    - imageDetail.json
    - appspec.yml
    - taskdef.json
