name: Deploy to Amazon S3 (dev)

on: 
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "22.3.0"
      
    - name: Check Node Version
      run: |
        node --version
        npm --version
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ap-northeast-1

    - name: Load Secrets from AWS Secrets Manager
      id: load-secrets
      run: |
        SECRETS=$(aws --region ap-northeast-1 secretsmanager get-secret-value \
        --secret-id ${{secrets.AWS_SECRETSMANAGER_ID}} | jq -r '.SecretString')
        echo "$SECRETS" | jq -r 'to_entries | map("\(.key)=\(.value|tostring)") | .[]' >> $GITHUB_ENV

    - name: Build
      run: |
        cd ./frontend
        npm install
        npm run build

    - name: S3 Sync
      run: |
        aws s3 sync ./build ${{ secrets.AWS_S3_BUCKET_NAME }} \
        --delete --cache-control "no-cache" \
        --region ap-northeast-1

    - name: Reset Cloud Front Cache
      run: |
        aws cloudfront create-invalidation \
        --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"